### ISSUE TITLE
The stage property of the StageWebView class is invalid.

### ISSUE THREAD

**Issue by xiaoChi888** [airsdk/Adobe-Runtime-Support#2339] opened 2022-12-06 20:46 UTC
I'm using SDK version 50.0.1.1 with Animate to develop an student project. I wanted to show the "about information" with HTML by StageWebView. But now I got a bug. The stage property of the StageWebView class is invalid. In a sense, the object actually uses the stage of initial window. When I set the stage property, it didn't matter, it didn't display on the window corresponding to the stage as expected.
The systemChrome of my initial window is "none" , stage.align is "TL", and stage.scaleMode is "noScale". The last two properties of the window I expected to display the StageWebView object are the same, the others options are default. When I set the stage property of the StageWebView object, the performance is it didn't display on any window, but the response area seems like it's on the initial window.
I'm just try to dev the program on Windows 10, I don't know would it reproduced on Macintosh. 
I plan to use this project for a college student discipline competition, and while this "about information" could have been implemented in other ways, I wanted to add the icing on the cake with HTML.
By the way, make fun of that access git in China is so troublesome, it's the first time I access git.

**Comment by ajwfrost** [comment] 2022-12-07 10:57
Hi

I thought we'd fixed this issue earlier - but having checked, it seems this is still a problem where it's using the original, IE-based StageWebView implementation (using the WebBrowser activex control which is similar to how Edge "IE Mode" works).

If you have Edge, and the Edge WebView2 component installed, then you can use this instead, and the bug is already fixed there: in your application descriptor, add a section:
```
	<windows>
		<UseWebView2>true</UseWebView2>
	</windows>
```
You'd need the app descriptor namespace to be 33.1 or higher for this.

If you're definitely needing to use this with the older IE-based WebView mechanism, we can look at the changes needed to fix this, it's a little more complex there though..


thanks

**Comment by xiaoChi888** [comment] 2022-12-07 14:52
Thanks for your reply. The program have ran as expected after i add the tag.
And now I have a question: how to make sure that I (the developer) or the user installed the Edge WebView2 component? What I'm saying is if I could test the program as expected, should i be worried about the program may run unexpectably on the user's device?

**Comment by xiaoChi888** [comment] 2022-12-07 16:03
Uh, even if i use the Edge WebView2, there's still some bug with `stageWebView.stage`…

There's concerned code of my project:

		private static var html: StageWebView = new StageWebView();
		private static var window: NativeWindow;
		private static const options: NativeWindowInitOptions = new NativeWindowInitOptions();

		public static function init() {
			options.type = NativeWindowType.UTILITY;
			html.loadURL("http://example");
			ContextMenuUtils.getItemByLabel("关于MapEditor").addEventListener(Event.SELECT, changeDisplayState);
		}
		private static function windowResize(e: Event) {
			html.viewPort = new Rectangle(0, 0, window.stage.stageWidth, window.stage.stageHeight);
		}
		private static function windowDeactivate(e: Event) {
			html.stage = null;
			trace(html.stage); //null
			window.close();
			ContextMenuUtils.getItemByLabel("关于MapEditor").checked = false;
		}
		private static function windowClose(e: Event) {
			window.removeEventListener(Event.DEACTIVATE, windowDeactivate);
			window.removeEventListener(Event.CLOSE, windowClose);
			window.stage.removeEventListener(Event.RESIZE, windowResize);
		}
		private static function changeDisplayState(e: Event) {
			window = new NativeWindow(options);
			window.title = "关于MapEditor";
			window.stage.align = StageAlign.TOP_LEFT;
			window.stage.scaleMode = StageScaleMode.NO_SCALE;
			window.stage.color = 0x313131;
			window.addEventListener(Event.DEACTIVATE, windowDeactivate);
			window.addEventListener(Event.CLOSE, windowClose);
			window.visible = true;
			html.stage = window.stage;
			trace(html.stage); //[object Stage], but the stageWebView don't show second time.
			html.viewPort = new Rectangle(0, 0, window.stage.stageWidth, window.stage.stageHeight);
			window.stage.addEventListener(Event.RESIZE, windowResize);
			ContextMenuUtils.getItemByLabel("关于MapEditor").checked = true;
			window.orderToFront();
		}

If i run the ActionScript, the stage property of StageWebView object only effective once. After the window closed, i instanced a new NativeWindow and try to set stage property with the new window's stage. But the StageWebView object didn't display.

**Comment by xiaoChi888** [comment] 2023-02-27 05:01
It got worse…
This is one of my program under AIR 50.1.1.2:
![image](https://user-images.githubusercontent.com/119972730/221477831-f12af0a2-d43d-4d0d-b27b-7afe2685bb5e.png)
And the following is the same ActionScript under AIR 50.2.1.1:
![image](https://user-images.githubusercontent.com/119972730/221477642-126360e5-c760-4fcc-8350-f3d7e9a16cfd.png)
The new version create a new window includes the webview, and it's left-top is [0, 0] of screen.
@ajwfrost

**Comment by ajwfrost** [comment] 2023-02-27 08:45
Hmm, I thought our testing included checking the `StageWebView.viewPort` settings.. can you confirm which version of the webview you're using there, and I'll get someone to double-check it here....

thanks

**Comment by ajwfrost** [comment] 2023-02-27 09:52
Hi -> viewPort works with the 'old' webview, but yes it seems like we don't adjust the position properly for webview2 ... 
Will get this one fixed asap...

thanks

**Comment by ajwfrost** [comment] 2023-02-28 18:25
Would you be able to check a potential fix for us please? This has been a tricky one to get right for every scenario, but we have a version now which is working for our test cases - but it would be good to have real-world confirmation!
https://transfer.harman.com/message/HpAfVQEsan8gfgfFJUdUMO

thanks

**Comment by xiaoChi888** [comment] 2023-03-01 05:34
Hello.

I test the new version with an easy ActionScript, the program behaved basically as expected, but i still found out a bug.

**OS:** Windows 10
**Edge Version:** 110.0.1587.57 (64bit) (Having checked, seems i didn't install WebView2 in addition.)

The following is the ActionScript used to be tested:


package {
	import flash.display.Sprite;
	import flash.media.StageWebView;
	import flash.geom.Rectangle;
	import flash.events.MouseEvent;
	import flash.events.Event;
	import flash.display.NativeWindow;
	import flash.display.NativeWindowInitOptions;
	import flash.events.NativeWindowBoundsEvent;

	public class WebViewTest extends Sprite {
		private const html: String = "<!doctype><head><style>body {	background-color :#999999;}</style></head><body><h1>WEBVIEW TEST</h1></body>"
		private const webView: StageWebView = new StageWebView();
		private var window: NativeWindow;
		private const options: NativeWindowInitOptions = new NativeWindowInitOptions();

		public function WebViewTest() {
			webView.loadString(html);
			webView.stage = stage;
			webView.viewPort = new Rectangle(0, 0, 400, 200);
			stage.addEventListener(MouseEvent.CLICK, changeWebViewStage);
		}
		private function changeWebViewStage(e: Event) {
			if (window) {
				window.removeEventListener(NativeWindowBoundsEvent.RESIZE, windowResize);
				window.close();
				window = null;
			}
			window = new NativeWindow(options);
			window.addEventListener(NativeWindowBoundsEvent.RESIZE, windowResize);
			window.activate();
			webView.stage = window.stage;
			trace(webView.viewPort.width + ", " + webView.viewPort.height); //Always has output, even if the webView lost.
		}
		private function windowResize(e: NativeWindowBoundsEvent) {
			webView.viewPort = new Rectangle(0, 0, e.target.stage.stageWidth, e.target.stage.stageHeight);
		}
	}

}



What i found out is that if the window which includes the webView has been closed (at the same time no new window hosting the webView), AIR would lost the webView.

**Comment by ajwfrost** [comment] 2023-03-03 14:09
Thanks for the info there. So, a workaround for this is that when the window is closing, you can set the webView.stage to null, and that should allow it to continue.. but we have also just checked and we can add that directly into the StageWebView class itself, making this automatic.

thanks

**Comment by xiaoChi888** [comment] 2023-03-04 13:56
Wait!! Seems there's still bugs in the potential fix over again…

There's a easy program to preview animations from a web game which based on Flash Player, public welfare, so i directly put release related source code.
I have tested it with WebView (IE-based?) and WebView2 (just Edge), seems the viewPort of WebView is wrong and some decision program with WebView2 is strange…

Related ActionScript goes here:


	package xiaoChi.Petdoctor {
	import flash.display.Sprite;
	import flash.events.MouseEvent;
	import flash.media.StageWebView;
	import flash.filesystem.FileStream;
	import flash.filesystem.File;
	import flash.filesystem.FileMode;
	import flash.geom.Rectangle;
	import flash.events.Event;
	import flash.events.NativeWindowBoundsEvent;

	public class InfoPanel extends Sprite {
		private var html: String;
		private const webView: StageWebView = new StageWebView();
		private var fileStream: FileStream = new FileStream();
		private var file: File = new File();

		public function InfoPanel() {
			file = File.applicationDirectory.resolvePath("resource/About_Petdoctor_2023.html");
			fileStream.addEventListener(Event.COMPLETE, fileOpened);
			fileStream.openAsync(file, FileMode.READ);
			this.closeButton.addEventListener("click", close);
		}
		private function fileOpened(e: Event) {
			fileStream.removeEventListener(Event.COMPLETE, fileOpened);
			html = fileStream.readMultiByte(fileStream.bytesAvailable, "utf-8");
			fileStream.close();
			file = null;
			fileStream = null;
			webView.loadString(html);
		}
		internal function open() {
			visible = true;
			show();
		}
		internal function close(e: MouseEvent): void {
			this.visible = false;
			hide();
		}
		private function show() {
			var scale: Number = 0;
			var spacing: Number = 0;
			webView.stage = stage;
			if (stage.nativeWindow) { //桌面版
				stage.nativeWindow.addEventListener(NativeWindowBoundsEvent.RESIZE, stageResize);
				stageResize(new NativeWindowBoundsEvent("resize"));
			} else { //移动版
				if (stage.stageWidth / stage.stageHeight > 960 / 560) {
					scale = stage.stageHeight / 560;
					spacing = (stage.stageWidth - scale * 960) / 2;
					webView.viewPort = new Rectangle(210 * scale + spacing, 180 * scale, 536 * scale, 228 * scale);
				} else if (stage.stageWidth / stage.stageHeight <= 960 / 560) {
					scale = stage.stageWidth / 960;
					spacing = (stage.stageHeight - scale * 560) / 2;
					webView.viewPort = new Rectangle(210 * scale, 180 * scale + spacing, 536 * scale, 228 * scale);
				}
			}
		}
		private function hide() {
			webView.stage = null;
		}
		private function stageResize(e: NativeWindowBoundsEvent) {
			var scale: Number = 0;
			var spacing: Number = 0;
			if (stage.stageWidth / stage.stageHeight > 960 / 560) {
				scale = stage.stageHeight / 560;
				spacing = (stage.stageWidth - scale * 960) / 2;
				webView.viewPort = new Rectangle(210 * scale + spacing, 180 * scale, 536 * scale, 228 * scale);
			} else if (stage.stageWidth / stage.stageHeight <= 960 / 560) {
				scale = stage.stageWidth / 960;
				spacing = (stage.stageHeight - scale * 560) / 2;
				webView.viewPort = new Rectangle(210 * scale, 180 * scale + spacing, 536 * scale, 228 * scale);
			} //it's the same program as above
		}
	}
	}


[Petdoctor 2023 AIR 50.2 potential fix with WebView.app.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/10888482/Petdoctor.2023.AIR.50.2.potential.fix.with.WebView.app.zip)
[Petdoctor 2023 AIR 50.2 potential fix with WebView2.app.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/10888483/Petdoctor.2023.AIR.50.2.potential.fix.with.WebView2.app.zip)

Click the button to execute function `open()`.
![image](https://user-images.githubusercontent.com/119972730/222905858-3bf86a72-5a87-4b1c-acee-a0fac32da872.png)

With WebView(IE-based), the behavior like:
![image](https://user-images.githubusercontent.com/119972730/222906052-06b72d64-0dde-48d8-9a87-059b8ccba1e8.png)

With WebView2, when execute the `stageResize()` with instantiated `NativeWindowBoundsEvent` by ActionScript, it's different with resize window by mouse.
![image](https://user-images.githubusercontent.com/119972730/222906181-cc659282-d672-4f14-b5ad-3ca9a5be359e.png)

@ajwfrost

**Comment by ajwfrost** [comment] 2023-03-06 09:51
Hi @xiaoChi888 

Thanks for those -> the first one with IE-based WebView, I think we can now fix, just need to regression-test it!

The second one: when we drag with the mouse to adjust the window size, we are seeing the underlying client window being rendered because the webview2 control is moving quicker than the rest of the page redraws. Not much that we can do about that I'm afraid -> it would be possible to work around perhaps in ActionScript, but if we eliminate that underlying client draw (hopefully we can make that window transparent) then it may be acceptable.

But, I'm not sure whether this would fix what you're seeing above. When you say that it's different when you execute the ActionScript-based resize vs a mouse resize, is that what you're showing in the screenshot? Is there a way to call this by pressing one of the buttons there?

thanks

**Comment by xiaoChi888** [comment] 2023-03-06 10:39
Good night, or? (It's just getting dark where i am…)

Maybe I didn't describe it clearly, so that you misunderstood my meaning, sorry. The second one is not WebView2 moving quicker than SWF content (it's not such a trouble). 

Like what i've commented, when you click the "道具" button, it would execute the function `open()`. It's not hard to see that, it calls `show()`, and in `show()` it calls the function `stageResize()` with a instantiated `NativeWindowBoundsEvent`, the event object is what i called 'instantiated by ActionScript'.

Before you click the "道具" button, resize the window with a size which different with the initial size. Then click the button you'll see the problem. In my ActionScript, it should execute the same program with ActionScript-based Event and mouse resize (They all executed by the function `stageResize()`).

Thanks.

**Comment by ajwfrost** [comment] 2023-03-06 11:04
Ah okay, thanks - I hadn't thought to look at your AS3 code above that to see how that had been happening.. I see what you mean.

So we can reproduce this, but when we trace out the values that are being passed in to the "viewport" property setter, these reflect what's then displayed on the screen:

resize smaller->
Requesting Win32WebView2 viewport -> (171, 169, 608, 355) (from set stage)
Requesting Win32WebView2 viewport -> (210, 180, 746, 408) (from set viewport)
212, 179 is where it displays but this is too far down/right

So it looks like the value is correct initially when the stage value is set, but then there's a set viewport which comes in with the wrong values. But, even when the webview is not on the screen, we are getting a lot of messages to set the viewport (which all look right). e.g.:
```
Initial display:
Requesting Win32WebView2 viewport -> (0, 0, 0, 0)
Requesting Win32WebView2 viewport -> (210, 180, 746, 408)
Close it and resize the window:
Requesting Win32WebView2 viewport -> (224, 185, 775, 420)
Requesting Win32WebView2 viewport -> (224, 185, 775, 420)
Requesting Win32WebView2 viewport -> (224, 185, 775, 420)
Requesting Win32WebView2 viewport -> (241, 214, 855, 475)
Requesting Win32WebView2 viewport -> (241, 214, 855, 475)
Requesting Win32WebView2 viewport -> (241, 214, 855, 475)
Requesting Win32WebView2 viewport -> (241, 214, 856, 476)
Requesting Win32WebView2 viewport -> (241, 214, 856, 476)
Requesting Win32WebView2 viewport -> (241, 214, 856, 476)
Requesting Win32WebView2 viewport -> (213, 177, 741, 402)
Requesting Win32WebView2 viewport -> (194, 150, 640, 340)
Requesting Win32WebView2 viewport -> (182, 129, 565, 292)
Requesting Win32WebView2 viewport -> (179, 116, 525, 263)
// display it again:
Requesting Win32WebView2 viewport -> (179, 116, 525, 263) << called because we update the viewport based on the previous values, when 'set stage' is called
Requesting Win32WebView2 viewport -> (210, 180, 746, 408) <<< from the AS3 code, but with wrong values?
```

So I'm wondering if there's something up in the logic that calculates the size, or whether it's getting an incorrect value from stageWidth etc? It seems odd that the viewport is coming in as 179,116 etc due to the window resize handler but then 210,180 when the 'show()' is called...

Are you able to add trace statements immediately before each of the "set viewport" calls, so that we know (a) which of these four calls are actually being called, and (b) what the rectangle values are that are being passed in?


thanks

**Comment by ajwfrost** [comment] 2023-03-06 11:41
Actually .. it looks like the stage width/height values are coming to you wrongly?!

After starting up and dragging the window larger, and then clicking for the 'show()' method:
```
Requesting Win32WebView2 viewport -> (0, 0, 0, 0)
get_stageWidth 1 -> 960
get_stageHeight 1 -> 560
get_stageWidth 1 -> 960
get_stageHeight 1 -> 560
get_stageWidth 1 -> 960
get_stageHeight 1 -> 560
Requesting Win32WebView2 viewport -> (210, 180, 746, 408)
```
and then slightly shrinking the window:
```
get_stageWidth 2 -> 1190
get_stageHeight 2 -> 909
get_stageWidth 2 -> 1190
get_stageHeight 2 -> 909
get_stageWidth 2 -> 1190
get_stageHeight 2 -> 909
Requesting Win32WebView2 viewport -> (260, 331, 924, 614)
Requesting Win32WebView2 viewport -> (260, 331, 924, 614)
Requesting Win32WebView2 viewport -> (260, 331, 924, 614)
```

The fact that the '1' and '2' appear in those traces means it's using a different mechanism to calculate them .. which is partly because you are checking the values within the resize event, I believe. I'm not sure why the values are (seemingly) wrong when we first get them in the 'show()' call though... will look into this!

**Comment by ajwfrost** [comment] 2023-03-06 11:51
Ah... so this is to do with your stage scale mode...

If you want to handle layouts yourself, you need to set the scale mode to 'noScale':
```
stage.scaleMode = StageScaleMode.NO_SCALE;
```
And then, when you resize the window, you will also resize the stage which means when you call stageWidth/stageHeight you will essentially get the window client size.

I think with the value you've got (showAll?) you aren't actually changing the stage size at all, it's always going to be the value that you set up originally when authoring the content (960x560).

The quirk is that in a NativeWindow 'resize' event, there is a special bit of code set up so that when you query the stage width or height within the event handler, you will get the window client coordinates. So I think to handle what you're trying to do, unless you switch the scaling mode, you'll need to cache the latest values that you get in the 'resize' handler and then use these directly in the call to setting the viewport, rather than just getting again the width/height from the stage object.

thanks

**Comment by xiaoChi888** [comment] 2023-03-06 11:53
Sorry for my poor English language… I'm not very sure your meaning, need i add `trace()` to output something? Please tell me what content need to output with codes, thanks.

For the different values of `stageWidth`/`stageHeight`, some of my thinking is, you have ignored the differ with different align ways (in my memory, some behavior of someone version earlier made me have the thinking), there is/are version(s) of AIR handle WebView as a way which's behavior is a little similar set "TL" and "noScale" to `stage.align` and `stage.scaleMode`.

**Comment by xiaoChi888** [comment] 2023-03-06 12:02
Uh, maybe i know what you mean.

So you think the bug is when calling `stageWidth`/`stageHeight`, returned values are wrong? If you look at the historical performance, it is true…? But there's a new problem in it(or maybe we need to call it 'old', because it existed a long time ago), that if the `stage.scaleMode` is "showAll", seems setter of `stageWidth`/`stageHeight` would 'refuse' set value, that means if u try to set those properties, they won't get change, and keep the old value.

**Comment by ajwfrost** [comment] 2023-03-06 14:07
Yes, so basically unless you have `stage.scaleMode` set to `noScale`  then `stageWidth` and `stageHeight` should be constant values based only on the SWF dimensions (at least, that's my understanding!). But then, the question is, should we be positioning the `StageWebView` object based on the stage-relative dimensions, or on the window-absolute dimensions.

Let me check on this further, as it may be that there's a simpler workaround. I was going to say; we should at least make it consistent between the IE-based WebView and the Edge-based WebView2, but then, it looks like this issue is present in both of your sample apps...!

**Comment by 2jfw** [comment] 2023-03-06 14:31
> 

On top of that: in order to correctly position and layout the `StageWebView` you also need to apply the `stage.contentsScaleFactor` for each of these

**Comment by 2jfw** [comment] 2023-03-06 15:02
> On top of that: in order to correctly position (_x, y, width, height_) the `StageWebView` you also need to apply the `stage.contentsScaleFactor` for each of these (see #1784)
> 
> **EDIT:** Added _x, y, width, height_ for clarification

I would actually think that the framework should do this, since this is the only component (afaik) which behaves differently when getting positioned, @ajwfrost ...

**Comment by xiaoChi888** [comment] 2023-03-06 15:16
> Yes, so basically unless you have `stage.scaleMode` set to `noScale` then `stageWidth` and `stageHeight` should be constant values based only on the SWF dimensions (at least, that's my understanding!). But then, the question is, should we be positioning the `StageWebView` object based on the stage-relative dimensions, or on the window-absolute dimensions.

I think… When i first started with ActionScript 3.0, i always think there should be some way (such as a property) to ensure SWF width and height for `stage.scaleMode = "showAll"`. It's different from `stage.stageWidth` and `stage.stageHeight`, those two are relative to SWF content, but there need some way to get a real value relative to window(?).

You know, the default value of `stage.scaleMode` is `showAll`, and maybe some people first start with ActionScript don't realize it. It's not easy to calculate the size of SWF content by `stage.nativeWindow.width`/`stage.nativeWindow.height` when the window has system chrome. And sometimes, for example, some game need fixed-size function buttons around game area but game content scalable with window size…

Besides, with my easy program where's one more bug that, when the WebView2 once be removed (`webView.stage = null`), resize the window, the WebView2 area would show a grey rectangle and text "WebView2 Host", can you reproduce it?

**Comment by ajwfrost** [comment] 2023-03-06 16:33
> I would actually think that the framework should do this, since this is the only component (afaik) which behaves differently when getting positioned

Hi @2jfw  - yes that's what I am also thinking! But slightly concerned we may then be changing code and breaking things for other people... but the documentation for [`StageWebView.viewPort`](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/StageWebView.html#viewPort) suggests that the coordinates are stage coordinates, rather than window system coordinates so I'm inclined to agree with you.

So then, the other part is within the native window resize event.. I have no idea why the AIR runtime deliberately (it seems) ensures the `stageWidth`/`stageHeight` values are wrong within this call, particularly when the actual window bounds are already available within that event object... but if we were to ensure `StageWebView` viewports really are based on the stage coords rather than the window ones, it may mean that the native window sizing is just irrelevant...

It all seems a bit of a mess :-(    We'll probably have to take some more time to look into this; as a short term update we can do a step to fix a number of the issues here but with the situation where `StageWebView` viewports are still based on the window coordinates, so you'd need to get these rather than the stage-positioning if you're using anything other than `noScale`.

thanks

**Comment by xiaoChi888** [comment] 2023-03-27 04:57
Hi.
 
Seems on Android with AIR 50.2.2.2, when set `StageWebView.stage` to `null`, the webView object isn't removed from content.
 
I have no means to ensure where the bug happens on real machine (the bug is feedback from the user), but i just add three `removeEventListener()` with `NativeWindowBoundsEvent` before `webView.stage = null`, and after reading API referance, i think the bug is not caused by my new added functions (During the development process, desktop testing and compilation were successful).
 
Thanks. @ajwfrost

**Closed** 2023-05-04 13:59 UTC
Labels: Bug
