### ISSUE TITLE
Issue with adl on 33.1.1.533

### ISSUE THREAD

**Issue by 42retfa** [airsdk/Adobe-Runtime-Support#950] opened 2021-07-05 14:24 UTC
Hello,

I just overlayed the Flex SDK 4.16.1 with the latest Harman AIR SDK 33.1.1.533 and I'm experiencing the same problem as described on #917 

Is there a workaround  for this issue ?

Thank you.

Vincent.
After24.

**Comment by ajwfrost** [comment] 2021-07-05 14:31
What OS are you using? This should have been fixed but it appears it only works on Windows now…

**Comment by 42retfa** [comment] 2021-07-05 14:41
Hello Andrew,

Thank you for this quick answer.

I'm using MacOS 11.4 with the latest version of Intellij.

The error only occurs with Flex mobile projects, Flex desktop seems to be not impacted.

Vincent.

**Comment by 42retfa** [comment] 2021-07-06 07:29
Hi Andrew,

Any news about this issue ?

Thank you.

Vincent.

**Comment by ajwfrost** [comment] 2021-07-06 08:38
We have a fix, we just need to do another release; currently trying to get a few other updates into it that have come up with the AAB support...

**Comment by 42retfa** [comment] 2021-07-06 08:40
Thanks for the update Andrew.

**Comment by teotigraphix** [comment] 2021-07-07 16:47
Thought I was going crazy. It takes about 30 seconds before the app main window pops up from IntelliJ. It happens on Window or Mobile configs in IDEA.

Switched back and forth from 406 to 533 and yes, 533 is a problem with lagging launches, were you aware of this @ajwfrost ?

**Comment by ajwfrost** [comment] 2021-07-07 22:35
@teotigraphix I've not come across this issue before.. are you saying that just running the app is taking a lot longer, or is this happening when it's first packaging it and then launching it? Is this even for a desktop Windows AIR project i.e. definitely not related to AAB, but just where it's compiling and then running the app under ADL?

A quick check of ADL and it seems to work pretty much immediately, so it would be good to understand what IDEA is actually doing during this time..

thanks

**Comment by teotigraphix** [comment] 2021-07-07 23:03
Ah, its in IntelliJ pressing Debug/Run. in 406 after compile it it starts immediately in IntelliJ . 

If I switch SDKs from 406 to 533, after pressing Debug or Run, it will build/compile perfectly normal, then after success, it's like the player/debugger is hanging to startup and it takes about 30 seconds before the native window shell shows(using 533 for debugging).

Note that it will "eventually" connect and then startup, but it is definitely something changed from 406 to 533 and I can reproduce it by just switching my build configs sdks back and forth. So when I get that hang, after it runs and I kill the process, I switch sdks to 406, compile and run, instant startup, native window shows perfect.

**Comment by teotigraphix** [comment] 2021-07-07 23:15
@ajwfrost  Also, I commented here because I thought it sounded something like issue #917

**Comment by teotigraphix** [comment] 2021-07-20 15:09
@ajwfrost Good news, the 554 fixed this issue, debug starts within seconds again! Peace.

**Comment by ajwfrost** [comment] 2021-07-20 15:30
@teotigraphix that's great to hear, although still a little concerning as we have no idea what could have caused the behavioural/performance change here!!

Just realised that this original issue was about the `-profile` support not working on macOS, which was fixed in 33.1.1.554 although we somehow missed that out of the release notes... closing this now then, but please re-open if you still see the problem.

thanks

**Closed by ajwfrost** 2021-07-20 15:30 UTC
Labels: Bug

**Comment by teotigraphix** [comment] 2021-07-20 15:34
Yeah sorry about that, I hijacked the issue weeks ago, this was affecting all profiles. I should have made another issue. :)
