### ISSUE TITLE
Sending msg to worker causes crash with AIR 33.1.1.86

### ISSUE THREAD

**Issue by gosgame** [airsdk/Adobe-Runtime-Support#286] opened 2020-03-31 14:52 UTC
## Problem Description

An error occurs after sending the first msg to a worker on a 64-bit Android package made with AIR SDK 33.1.1.86. 
The worker is initialized successfully but after the first message send a native crash occurs.
The 32-bit android package works fine with the same build and SDK.

Apk is created on a Windows 10 pc and tested on an Android 9 - Samsung Galaxy S8 device.

Logcat output;

03-31 15:36:45.921 24713 24713 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 24713 (.mobile.fashcup), pid 24713 (.mobile.fashcup)
03-31 15:36:45.922 24713 24944 I AIRuntimeCheck: AIR - removing splash screen
03-31 15:36:45.989 22959 22962 E nightwatch-watcher: Failed to read from logcat: Success
03-31 15:36:45.989 22391 22393 E nightwatch-watcher: Failed to read from logcat: Success
03-31 15:36:46.013 24951 24951 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
03-31 15:36:46.017  5042  5042 I /system/bin/tombstoned: received crash request for pid 24713
03-31 15:36:46.019 24951 24951 I crash_dump64: performing dump of process 24713 (target tid = 24713)
03-31 15:36:46.028 24951 24951 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-31 15:36:46.028 24951 24951 F DEBUG   : Build fingerprint: 'samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXS6DTA1:user/release-keys'
03-31 15:36:46.028 24951 24951 F DEBUG   : Revision: '10'
03-31 15:36:46.028 24951 24951 F DEBUG   : ABI: 'arm64'
03-31 15:36:46.028 24951 24951 F DEBUG   : pid: 24713, tid: 24713, name: .mobile.fashcup  >>> air.com.gamegos.mobile.fashcup <<<
03-31 15:36:46.028 24951 24951 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
03-31 15:36:46.028 24951 24951 F DEBUG   : Cause: null pointer dereference
03-31 15:36:46.028 24951 24951 F DEBUG   :     x0  0000007495113fc4  x1  0000007fe0531470  x2  0000000000000000  x3  0000000000000000
03-31 15:36:46.028 24951 24951 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  fffffffd07f2f7ee
03-31 15:36:46.028 24951 24951 F DEBUG   :     x8  0000000000000000  x9  00000000deadbeef  x10 0000000000004002  x11 0000000000000000
03-31 15:36:46.028 24951 24951 F DEBUG   :     x12 000000748d65099a  x13 000000009a85eb4b  x14 0000007492437000  x15 0000000000000003
03-31 15:36:46.028 24951 24951 F DEBUG   :     x16 0000007536b6f210  x17 0000007536a9eed0  x18 0000000000000000  x19 00000074927e9eb8
03-31 15:36:46.028 24951 24951 F DEBUG   :     x20 0000007492437000  x21 0000000000000001  x22 0000000000000003  x23 0000007495c5e0e0
03-31 15:36:46.028 24951 24951 F DEBUG   :     x24 0000007fe0532168  x25 0000007fe0532130  x26 000000748fe4bdc5  x27 0000007fe0532158
03-31 15:36:46.028 24951 24951 F DEBUG   :     x28 000000748d3b9fa8  x29 0000007fe0531550
03-31 15:36:46.028 24951 24951 F DEBUG   :     sp  0000007fe0531520  lr  00000074951118b8  pc  0000007495111914
03-31 15:36:46.038 24951 24951 F DEBUG   : 
03-31 15:36:46.038 24951 24951 F DEBUG   : backtrace:
03-31 15:36:46.038 24951 24951 F DEBUG   :     #00 pc 00000000007ac914  /data/app/air.com.gamegos.mobile.fashcup-G5T8_pePZxtZYvvXV1pp8w==/lib/arm64/libCore.so
03-31 15:36:46.038 24951 24951 F DEBUG   :     #01 pc 0000000000008f44  <anonymous:000000748d019000>

**Comment by ajwfrost** [comment] 2020-04-02 15:19
Hi - we've not been able to reproduce this. Would it be possible for you to package up your application with "apk-debug" and then send it to me using the below link?  thanks
https://transfer.harman.com/requests/fZTur4UaTyGx2zcd9tOhAd

**Comment by gosgame** [comment] 2020-04-03 13:13
I think I have encapsulated the case. A native crash occurs when the worker thread writes to a shareable bytearray while the main thread is busy. Only 64bit packages cause this error, 32bits are fine. I am sending you the test code which you can trigger an error by pressing the screen multiple times.

```as3
package
{
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.events.MouseEvent;
	import flash.system.Worker;
	import flash.system.WorkerDomain;
	import flash.utils.ByteArray;
	import flash.system.MessageChannel;
	import flash.utils.getTimer;

	public class Main extends Sprite
	{
		private var _msgCount:int = 0;

		private var _worker:Worker;
		private var _mainToWorker:MessageChannel;

		private var _bytes:ByteArray;
		
		public function Main():void
		{
			if (stage)
			{
				init();
			}
			else
			{
				addEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
			}
		}
		
		private function onAddedToStage(e:flash.events.Event):void
		{
			removeEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
			
			init();
		}
		
		private function init():void
		{
			if (Worker.current.isPrimordial) // entry point for the main thread
			{
				trace("Main - Primordial");

				stage.addEventListener(Event.ENTER_FRAME, onEnterFrame);
				stage.addEventListener(MouseEvent.MOUSE_DOWN, onStageClicked);

				_bytes = new ByteArray();
				_bytes.shareable = true;	

				var swfBytes:ByteArray = this.loaderInfo.bytes;
				_worker = WorkerDomain.current.createWorker(swfBytes, true);
				
				_mainToWorker = Worker.current.createMessageChannel(_worker);
				_worker.setSharedProperty("mainToWorker", _mainToWorker);
				
				_worker.start();	
			}
			else // entry point for the background worker
			{
				trace("Main - Worker");

				_mainToWorker = Worker.current.getSharedProperty("mainToWorker");
	
				_mainToWorker.addEventListener(Event.CHANNEL_MESSAGE, _onWorkerMessage);
			}
		}

		private function onStageClicked(e:MouseEvent):void
		{
			++_msgCount;
			trace("Main - onStageClicked. msgCount: " + _msgCount);

			_mainToWorker.send(_bytes);
		}

		private function onEnterFrame(e:Event):void 
		{
			var startTime:int = getTimer();
			while (true) // keep main thread busy
			{
				if (getTimer() - startTime > 100) {
					break;
				}
			}
		}

        private function _onWorkerMessage(e:Event):void
        {
            var obj:Object = _mainToWorker.receive();
			
			if (obj is ByteArray) 
			{
				var bytes:ByteArray = obj as ByteArray;

				trace("Worker - ByteArray received: " + bytes.length);
				
				bytes.clear();
			}		
        }
	}
}
```

**Comment by ajwfrost** [comment] 2020-04-05 06:23
Great thanks - so yes, we can reproduce this and can see it's because of a change in length of the shared bytearray - if you don't call 'clear', it should be okay.

As a workaround, if you're able to keep the length the same (set it high during initialisation perhaps?) and just use some other mechanism to determine what bytes are being sent for processing, this would help.

Fixing the underlying issue is going to be a little challenging as there are security implications and when the code is JITted into machine code, we will have to add a few more checks/steps to ensure appropriate thread-safety..  we'll look into this to see how best to approach it.

thanks

**Comment by gosgame** [comment] 2020-04-06 09:03
We use workers for file loading so we don't know the bytearray length in advance. There will be a memory overhead for setting them for the maximum possible size. We can wait for your solution otherwise we may have to disable the worker loader for 64 bits.

Thank you for your help.

**Comment by ajwfrost** [comment] 2020-04-06 14:05
I think in the short term we may have a solution where we wait for the JITted function to complete, and then we can perform the necessary synchronisation.. will see if that helps here. At most this means that the 'clear' call would wait until the other worker's active AS3 function has finished so in your sample, the _onWorkerMessage function would pause within the "clear" method until the onStageClicked function has finished. (This also probably explains why you have to click a couple of times before seeing the issue: the onStageClicked function won't have been jitted the first time it's called, it's only when we've ended up in a JIT call that we have this problem..)

**Comment by gosgame** [comment] 2020-04-07 07:46
I would like to make it clear that the crash is not specific to bytearray.clear function. Changing clear to writeutfbytes function also causes a crash.

Waiting for the main thread may slow down the worker thread considerably if that's what you suggest. But still better nothing.

**Comment by ajwfrost** [comment] 2020-04-07 12:32
Yes, this happens at any point when the size of the bytearray is adjusted. So 'clear' takes the length down to zero; 'writeutfbytes' adds capacity to it, etc.

In your example, when the main thread's event handler has completed, we would be able to process the 'clear' call. It's not ideal - we're making AS3 functions non-interruptable, which stops the 'actionscript stuck' feature from working, but it should be okay for the short term. The danger might be if you have a function in one thread that's wanting to 'clear', and meanwhile we're already in another AS3 function in another thread which then wants to change the length too... I will check that whilst waiting to perform one of these tasks, they are then able to cope with such an issue and avoid deadlock!

thanks

**Comment by hardcoremore** [comment] 2020-04-07 16:38
Hi Andrew,

>  which stops the 'actionscript stuck' feature from working

Can you tell a little more about this feature. I never heard of it before.

Thanks.

**Comment by ajwfrost** [comment] 2020-04-07 18:27
Error code 1502 I believe: see
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/errors/ScriptTimeoutError.html

I think you can override the default timeout in some authoring tools like Animate; if you look in the SWF spec for "ScriptLimits" you'll find the details.

Basically the idea is to protect against a "while(1);" situation. It'll throw out that bit of code and stop the runtime from being a complete CPU hog..

**Comment by gosgame** [comment] 2020-04-15 14:56
Hi Andrew. 

After AIR 33.1.1.98, my test app stopped crashing. But our game app continues to crash. I couldn't reproduce the case in my test app. I am sending you the apk-debug package of our game by the link you provided in case you can figure out something. 

Thank you.

**Comment by gosgame** [comment] 2020-04-15 14:57
Unfortunately, the link has expired. Could you send me a new one?

**Comment by hardcoremore** [comment] 2020-04-15 16:55
Hi @ajwfrost ,

What happened to AIR 33.1.1.98? The harman AIR site is now pointing to 33.1.1.86

**Comment by ajwfrost** [comment] 2020-04-16 06:37
@hardcoremore I've asked our website guy to fix that; a refresh of the site managed to drop the updated text, but the zip file downloads are still of .98..

@gosgame will do, thanks..

**Comment by gosgame** [comment] 2020-04-17 13:16
@ajwfrost can you send me a new upload link? Other one says it is already used. Thanks.

**Comment by ajwfrost** [comment] 2020-04-20 06:43
@gosgame  sorry for the delay: please use 
https://transfer.harman.com/requests/TH7zg1k5QNlNYyGCgRLbCe

**Comment by gosgame** [comment] 2020-05-04 11:38
Hi @ajwfrost could you find something from the package I sent? If not I would like to know if you have any further plans for workers.

**Comment by gosgame** [comment] 2020-05-15 17:06
@ajwfrost  I have created a new test project which creates a native crash. AIR version is 33.1.1.98. You need to tap on the screen multiple times in order to see the crash.

I am not sure if this is the case in our game but it may help to solve it. Again the crashes occur only on 64-bit android builds not on 32-bit.

```as3
package
{
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.events.MouseEvent;
	import flash.system.Worker;
	import flash.system.WorkerDomain;
	import flash.utils.ByteArray;
	import flash.system.MessageChannel;

	public class Main extends Sprite
	{
		private var _sentCount:int = 0;

		private var _worker:Worker;
		private var _mainToWorker:MessageChannel;
		private var _workerToMain:MessageChannel;

		private var _bytesList:Array;
		
		public function Main():void
		{
			if (stage)
			{
				init();
			}
			else
			{
				addEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
			}
		}
		
		private function onAddedToStage(e:flash.events.Event):void
		{
			removeEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
			
			init();
		}
		
		private function init():void
		{
			if (Worker.current.isPrimordial) // entry point for the main thread
			{
				trace("Main - Primordial");

				stage.addEventListener(MouseEvent.MOUSE_DOWN, onStageClicked);

				_bytesList = new Array();
				for(var i:int = 0; i < 50; i++)
				{
					var bytes:ByteArray = new ByteArray();
					bytes.shareable = true;
					_bytesList.push(bytes);
				}

				var swfBytes:ByteArray = this.loaderInfo.bytes;
				_worker = WorkerDomain.current.createWorker(swfBytes, true);
				
				_workerToMain = _worker.createMessageChannel(Worker.current);
				_worker.setSharedProperty("workerToMain", _workerToMain);
				_mainToWorker = Worker.current.createMessageChannel(_worker);
				_worker.setSharedProperty("mainToWorker", _mainToWorker);
				
				_worker.start();	
			}
			else // entry point for the background worker
			{
				trace("Main - Worker");

				_mainToWorker = Worker.current.getSharedProperty("mainToWorker");
				_workerToMain = Worker.current.getSharedProperty("workerToMain");
	
				_mainToWorker.addEventListener(Event.CHANNEL_MESSAGE, _onWorkerMessage);
			}
		}

		private function onStageClicked(e:MouseEvent):void
		{
			trace("onStageClicked - 1. Start: " + (++_sentCount));

			for each(var byte:Object in _bytesList)
				_mainToWorker.send(byte);

			trace("onStageClicked - 2. Clearing bytes.");

			for each(byte in _bytesList)
				byte.clear();

			trace("onStageClicked - 3. Bytes cleared.");
		}

        private function _onWorkerMessage(e:Event):void
        {
            var obj:Object = _mainToWorker.receive();
			
			if (obj is ByteArray) 
			{
				var bytes:ByteArray = obj as ByteArray;

				for (var i:int = 0; i < 10; i++)
					_workerToMain.send("OK!");

				trace("_onWorkerMessage - 2. Clearing bytes.");

				bytes.clear();

				trace("_onWorkerMessage - 3. Bytes cleared.");
			}		
        }
	}
}
```

**Comment by ajwfrost** [comment] 2020-05-15 19:17
@gosgame  thanks for the test app - had a quick look and we're hitting the same problem as before, but coming from a different angle (not even jitted code!) - so we may be able to apply the same sort of "workaround". But better would be if we implemented this properly... We've gathered a little more information about this synchronisation process now so we will have a go at implementing it which should allow us to drop the earlier workaround, and provide a better/more performant fix to all these Worker/ByteArray issues..

thanks

**Comment by gosgame** [comment] 2020-08-17 14:36
@ajwfrost Hi, are there any updates or plans related to this issue? We will have to disable the worker functionality for 64bit devices if we achieve no solution. Thanks.

**Comment by ajwfrost** [comment] 2020-09-23 17:21
Hi - @gosgame  apologies for the delay, we do have an implementation for this now, so this will be fixed in our next release.

**Closed** 2021-06-23 13:56 UTC
Labels: Bug, Platform: Android, Runtime: AIR
