### ISSUE TITLE
Korean have exceptions on Android 12

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#1377] opened 2021-11-23 01:24 UTC
The APK packaged by AIR SDK, Korean can not be displayed normally on Android 12, but can be displayed normally on Android 11 and previous versions.
![QQ图片20211123092159](https://user-images.githubusercontent.com/1818875/142958431-db165abc-796d-4209-b80f-2e658b9ed2b3.jpg)
on Android 12

![微信图片_20211123092234](https://user-images.githubusercontent.com/1818875/142958457-b104e72f-1c84-445f-8b81-ed51cba2faa1.jpg)
on Android 11 and previous versions

**Comment by wmtj** [comment] 2021-11-28 01:28
I hope Harman will fix this bug as soon as possible. @ajwfrost

**Comment by ac27437676** [comment] 2022-04-01 05:16
I have the same problem,do you deal it?

**Comment by ajwfrost** [comment] 2022-04-01 06:49
Ah - this looks like it's a duplicate of #1299 so yes that should be working fine now if you get the latest AIR SDK.
thanks

**Closed** 2024-04-15 01:42 UTC
Labels: Bug
