### ISSUE TITLE
Has Adobe AIR SDK call these APIs default ? Apple has made new regulations on the use of these interfaces.

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#3151] opened 2024-04-01 10:15 UTC
We encountered the following warning during the review process from Apple.We are not sure if Adobe Air SDK has accessed these APIs by default.Can access be disabled by default? Then we don't need to access these APIs.

ITMS-91053: Missing API declaration - Your app’s code in the “ENYTTX” file references one or more APIs that require reasons, including the following API categories: **NSPrivacyAccessedAPICategoryDiskSpace**. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “ENYTTX” file references one or more APIs that require reasons, including the following API categories: **NSPrivacyAccessedAPICategoryFileTimestamp**. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “ENYTTX” file references one or more APIs that require reasons, including the following API categories: **NSPrivacyAccessedAPICategorySystemBootTime**. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “ENYTTX” file references one or more APIs that require reasons, including the following API categories: **NSPrivacyAccessedAPICategoryUserDefaults**. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

**Comment by marchbold** [comment] 2024-04-02 01:10
Duplicate of https://github.com/airsdk/Adobe-Runtime-Support/issues/3116

**Closed by marchbold** 2024-04-02 01:10 UTC
Labels: Bug

**Comment by marchbold** [comment] 2024-04-02 01:11
For an immediate solution add a file `PrivacyInfo.xcprivacy` to your app with the content in the linked issue above. 

Long term, Harman are working on an automatic solution as part of the AIR build process.
