### ISSUE TITLE
aapt tool failed Android apk build

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#1794] opened 2022-03-23 11:09 UTC
Hi @ajwfrost, hope you are doing fine.

I am trying to build an APK with the latest ANEs of distriqt and SDK 33.1.1.795
Unfortunately I receive this error:
aapt tool failed:/private/var/folders/cl/zvbhs0x54_nbsbmk27h4v1tr0000gp/T/ebaec74e-0de1-4a95-8206-d8dc21ef805b/savedstate-1.1.0-res/values/values.xml:3: error: Found tag id where item is expected

/private/var/folders/cl/zvbhs0x54_nbsbmk27h4v1tr0000gp/T/ebaec74e-0de1-4a95-8206-d8dc21ef805b/lifecycle-viewmodel-2.4.1-res/values/values.xml:3: error: Found tag id where item is expected

/private/var/folders/cl/zvbhs0x54_nbsbmk27h4v1tr0000gp/T/ebaec74e-0de1-4a95-8206-d8dc21ef805b/lifecycle-runtime-2.4.1-res/values/values.xml:3: error: Found tag id where item is expected

/private/var/folders/cl/zvbhs0x54_nbsbmk27h4v1tr0000gp/T/ebaec74e-0de1-4a95-8206-d8dc21ef805b/constraintlayout-2.1.3-res/values/values.xml:1491: error: Attribute "android:translationX" has already been defined
/private/var/folders/cl/zvbhs0x54_nbsbmk27h4v1tr0000gp/T/ebaec74e-0de1-4a95-8206-d8dc21ef805b/constraintlayout-2.1.3-res/values/values.xml:1495: error: Attribute "android:translationY" has already been defined
/private/var/folders/cl/zvbhs0x54_nbsbmk27h4v1tr0000gp/T/ebaec74e-0de1-4a95-8206-d8dc21ef805b/constraintlayout-2.1.3-res/values/values.xml:1498: error: Attribute "android:translationZ" has already been defined

Adding the link on my mac: /Users/myMac/Library/Android/sdk
I get the error: too many SDKs use the latest.
Using the link to the latest I get this error:
Could not locate adb: /Users/myMac/Library/Android/sdk/build-tools/32.0.0/platform-tools/adb

I am using FDT as development platform.

I tried to copy the adt.jar file which I downloaded and deactivated <BuildLegacyAPK>true</BuildLegacyAPK> as mentioned at this link: https://github.com/airsdk/Adobe-Runtime-Support/discussions/1782

But unfortunately nothing seems to work.

How Can I resolve this problem? Thank you for help in advance.

**Comment by Braisor** [comment] 2022-03-23 16:12
https://github.com/airsdk/Adobe-Runtime-Support/discussions/1762#discussioncomment-2338157

**Comment by Dima107** [comment] 2022-03-23 18:50
I have the same issue. But not for 795 only. I've got this error after updating Advert.ane (and dependencies)
But aab works good.
https://github.com/distriqt/ANE-Adverts/issues/372

**Comment by apofis1969** [comment] 2022-03-24 10:48
I need the apk build working. It is much easier for testing. I hope @ajwfrost will send a solution soon. I have a lot of ANEs in my app.

**Comment by apofis1969** [comment] 2022-03-25 13:03
Hi @ajwfrost, I tried to build an aab package and now I get the error:
Packaging failed!
Packaging error message: 
no such file /Users/myMac/Documents/Arbeitsplatz/a-MyApp/fdt/MyApp_AndroidX_42/pkcs12

What can I do? Can you please also tell me how to resolve the apk build? It is a big frustration already.

**Comment by ajwfrost** [comment] 2022-03-25 23:28
Hi @apofis1969 

For this one:

> Could not locate adb: /Users/myMac/Library/Android/sdk/build-tools/32.0.0/platform-tools/adb

Are you able to find out where ADB actually is? I would actually expect it to be in:

`/Users/myMac/Library/Android/sdk/platform-tools/adb`

i.e. not in `build-tools` but just in the SDK root then `platform-tools`.


For this:

> no such file /Users/myMac/Documents/Arbeitsplatz/a-MyApp/fdt/MyApp_AndroidX_42/pkcs12

it sounds like something is wrong with the packaging command line and it's interpreting "pkcs12" as a filename rather than as the storetype variable. Are you able to double-check your command line or the tool set-up? You can also see ow ADT is being invoked if you set up (or uncomment) the `DebugOut=true` line from the adt.cfg file in your SDK's "lib" folder, and then view the log output in `/Users/myMac/adt.log`

thanks

**Comment by apofis1969** [comment] 2022-03-26 15:01
Hi, @ajwfrost I am able to create apk and aab now. The aab is only working via the command-line tool.
Can you please tell me how to correctly use the -installApp command so that I can test the aab build on my device without waiting hours until the build at the internal testing on Google Play Developer is available? Thank you for your help.

**Comment by ajwfrost** [comment] 2022-03-29 14:47
AABs can be installed in the same way as APKs with the '-installApp' command:
```
adt -installApp -platform android -package MyAppFile.aab
```

As long as the file extension is `aab` then this will use the Android bundletool library to extract the APKS from the AAB file and to install these onto the connected handset.

thanks

**Comment by raresn** [comment] 2022-03-29 15:03
@ajwfrost kinda related to this, is there a way to speed this install process up?
It takes 2 minutes to compile the aab and 2 minutes to install. 
Would be cool to be able to do this faster.

**Comment by ajwfrost** [comment] 2022-03-29 16:43
Sorry, we just use the Android tools. There may be some speed-up when recompiling the AAB file if you were able to do this from inside Android Studio; we use the "no-daemon" approach with Gradle because we kept running into problems when trying to re-compile it if it was using a daemon, so this may slow it down a little.

The install is slow but is just the same as when using Android tools (bundletool/adb) as all we're doing is calling out to those, it's a convenience wrapper really..

thanks

**Comment by raresn** [comment] 2022-03-29 19:17
No probs! 
Super glad you guys are committed to making AIR keep up with the rest of the world!
I can't emphasize enough how much this means to my team personally, and to the whole community

"This is the way!"

**Comment by Klug76** [comment] 2022-04-04 11:44
I have the same problem when trying to build apk for amazon (while aab for google play builds without errors, but amazon doesn't accept aab format).
AIR version: 795
Error log:
```
ADT exception: aapt tool failed:E:\temp\87246ea0-12c1-4ad0-919c-c29ec0fb7fff\androidx.lifecycle-lifecycle-viewmodel-2.3.1-res\values\values.xml:3: error: Found tag id where item is expected

E:\temp\87246ea0-12c1-4ad0-919c-c29ec0fb7fff\androidx.lifecycle-lifecycle-runtime-2.3.1-res\values\values.xml:3: error: Found tag id where item is expected

E:\temp\87246ea0-12c1-4ad0-919c-c29ec0fb7fff\androidx.savedstate-savedstate-1.1.0-res\values\values.xml:3: error: Found tag id where item is expected

E:\temp\87246ea0-12c1-4ad0-919c-c29ec0fb7fff\androidx.constraintlayout-constraintlayout-2.1.2-res\values\values.xml:1483: error: Attribute "android:translationX" has already been defined
E:\temp\87246ea0-12c1-4ad0-919c-c29ec0fb7fff\androidx.constraintlayout-constraintlayout-2.1.2-res\values\values.xml:1487: error: Attribute "android:translationY" has already been defined
E:\temp\87246ea0-12c1-4ad0-919c-c29ec0fb7fff\androidx.constraintlayout-constraintlayout-2.1.2-res\values\values.xml:1490: error: Attribute "android:translationZ" has already been defined
```

**Comment by ajwfrost** [comment] 2022-04-04 15:35
@Klug76 I would be interested to know which AAPT tool is being run there ... are you able to enable debug output from ADT (via the configuration file in the AIR SDK "lib" folder, adt.cfg, setting/uncommenting `DebugOut=true`) and then reproduce this, then send us the log from `c:\users\username\adt.log`?

thanks

**Comment by apofis1969** [comment] 2022-04-04 15:40
Hi @ajwfrost, I want to say thank you for your support. Could successfully build an aab and send to my devices for testing. I am upgrading my tablet now to Android 12.  It seems all to work. Thank you!!

**Comment by ac27437676** [comment] 2022-04-06 06:24
I have same problem,when use androidx.core.ane。
AIR version: 795

aapt tool failed:G:\tmp\2724441a-9c36-484e-8edf-731c2428efe3\savedstate-1.1.0-res\values\values.xml:3: error: Found tag id where item is expected
G:\tmp\2724441a-9c36-484e-8edf-731c2428efe3\lifecycle-viewmodel-2.4.1-res\values\values.xml:3: error: Found tag id where item is expected
G:\tmp\2724441a-9c36-484e-8edf-731c2428efe3\lifecycle-runtime-2.4.1-res\values\values.xml:3: error: Found tag id where item is expected

how i can fix the problem?thank you!

**Comment by ajwfrost** [comment] 2022-04-06 09:08
I think the issue here would be resolved if you use the new build mechanism for APK/AAB files.. so if you can ensure you've got Android Studio and have downloaded the Android SDK, you'll then need to ensure you have your application descriptor set to the 33.1 namespace ... if it's still not working, please enable the debug log (in SDK\lib folder "adt.cfg" file, uncomment `DebugOut=true`) and then re-try it, then post the contents of `c:\users\username\adt.log`
thanks

**Comment by ajwfrost** [comment] 2022-04-06 09:18
... just a quick update, yes it appears that the latest androidx libraries are no longer compatible with the "aapt" tool, so you would need to switch to use the new build process in order to resolve this.

thanks

**Comment by marchbold** [comment] 2022-04-06 22:53
@apofis1969 Just a note from our side, this error is caused by using the legacy apk build method. Our latest extensions require the new build method. 

I started a discussion on it here: https://github.com/airsdk/Adobe-Runtime-Support/discussions/1782

**Comment by ronyarbiv** [comment] 2022-05-19 11:24
Hi,

I am using the latest Air sdk, Latest Distriqt Anes.
I am using Intellij latest version.

From Intellij ->Build -> Packaging Air application I am manage to pack the apk.
The problem is that when i extract the apk to see the content, it seems like it contain only the swc of every Ane. 
the apk is 10 mb less the expected. 

several questions- 

1. Can i still package apps with intellij? (for simplisity i have temporarly signed the app with temporarly key and not my p12 key, and remove 1.8 java from the machine and from the enviromental variabel, i have installed android studio and android sdk)
2. The app is really old (but it still get alot of downloads every day) so it uses 1024 p12 key. so as far that i know inorder tho pack it i need to use the old java 1.8. i don't know if it means that i will not be able to combine android 31 support with the old java and the atest anes?

**Comment by yong2khoo88** [comment] 2022-07-11 06:52
> ... just a quick update, yes it appears that the latest androidx libraries are no longer compatible with the "aapt" tool, so you would need to switch to use the new build process in order to resolve this.
> 
> thanks

Hi I would like to know, what do you mean by 'switch to use the new build process'?

Here I am using Adobe AIRSDK 33.1.889, to build android app.
I updated all ANEs (basically Adverts and dependencies with APM cli).
I also create a whole new descriptor with APM, with 33.1.

Still, I am hitting the error
![image](https://user-images.githubusercontent.com/5007089/178205028-0c20729e-8ca8-4548-a008-1ecb9c2272b0.png)

I even tried replaced the adt.jar with the one from the forum discussion about the version AIRSDK 33.1.795, to the existing x.1.889. Still same error appear.

Here's my adt.log
```
Stack trace:
*** ADT Logging at 2022/07/11 14:47:44 ***
Called by: C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\adt.jar
APK Packager entry point
AAPT command line: C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\android\bin\aapt.exe package -z -u -J C:\Users\yong2\AppData\Local\Temp\954f4de1-28f7-479b-a797-c1c553060544 -M C:\Users\yong2\AppData\Local\Temp\954f4de1-28f7-479b-a797-c1c553060544\AndroidManifest.xml -S C:\Users\yong2\AppData\Local\Temp\954f4de1-28f7-479b-a797-c1c553060544\app_entry_res -S C:\Users\yong2\AppData\Local\Temp\954f4de1-28f7-479b-a797-c1c553060544\captive_runtime_res -m --extra-packages androidx.constraintlayout.widget:com.google.android.gms.ads.impl:com.google.android.gms.ads:androidx.coordinatorlayout:androidx.core:androidx.media:androidx.drawerlayout:androidx.fragment:androidx.startup:androidx.viewpager2:androidx.lifecycle.runtime:androidx.lifecycle.viewmodel:androidx.savedstate:com.distriqt.extension.core:androidx.browser:androidx.work:com.distriqt.extension.adverts:com.google.android.gms.base:com.google.android.gms.common:androidx.appcompat:androidx.appcompat.resources: -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\constraintlayout-2.1.3-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\play-services-ads-21.0.0-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\play-services-ads-lite-21.0.0-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\coordinatorlayout-1.1.0-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\core-1.6.0-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\drawerlayout-1.1.1-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\fragment-1.3.6-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\lifecycle-runtime-2.4.1-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\lifecycle-viewmodel-2.4.1-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\media-1.4.3-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\savedstate-1.1.0-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\startup-runtime-1.1.1-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\viewpager2-1.0.0-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\distriqt-extension-core-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\browser-1.3.0-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\work-runtime-2.7.0-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\distriqt-extension-adverts-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\play-services-base-18.0.1-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\play-services-basement-18.0.0-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\appcompat-1.4.1-res -S C:\Users\yong2\AppData\Local\Temp\2c004afd-c8ef-4c56-8187-6248ad49089f\appcompat-resources-1.4.1-res --auto-add-overlay -I C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\android\lib\resources\android-res.jar --no-version-vectors --min-sdk-version 14 --target-sdk-version 31 --version-code 62 --version-name 0.0.62 -F C:\Users\yong2\AppData\Local\Temp\954f4de1-28f7-479b-a797-c1c553060544\resources.apk
..java.lang.Thread.getStackTrace(Thread.java:1556)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.ADTException.<init>(ADTException.java)
..com.adobe.air.apk.APKOutputStream.a(APKOutputStream.java)
..com.adobe.air.apk.APKOutputStream.addApplicationDescriptor(APKOutputStream.java)
..com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.flexbuilder.multisdk.apollo.export.AIRAPKPackager.createUsingPackager(AIRAPKPackager.java:245)
..com.adobe.flexbuilder.multisdk.apollo.export.AIRAPKPackager.create(AIRAPKPackager.java:575)
..com.adobe.flexide.multiplatform.android.exportrelease.AndroidExportReleaseHandler.createPackage(AndroidExportReleaseHandler.java:352)
..com.adobe.flexide.multiplatform.android.exportrelease.AndroidExportReleaseHandler.doPackage(AndroidExportReleaseHandler.java:258)
..com.adobe.flashbuilder.project.multiplatform.ui.exportrelease.MultiPlatformExportReleaseVersionManager.doExport(MultiPlatformExportReleaseVersionManager.java:317)
..com.adobe.flexbuilder.exportimport.releaseversion.ui.ExportReleaseVersionWizard$1.run(ExportReleaseVersionWizard.java:221)
Stack trace:

```


adt.cfg file

```
# See release notes: uncomment these lines in order to force your APK to be generated with 64-bit ARM binaries
# (needed when using an IDE such as Adobe Animate that currently only provides armv7 and x86 as the options via the UI)
DefaultArch=armv8
OverrideArch=armv8

# See release notes and https://github.com/Gamua/Adobe-Runtime-Support/issues/58
#UncompressedExtensions=emd,tfl,tflite,pb

# Default is to prefiix the package with 'air.' - to turn this off, uncomment the below line
#AddAirToAppID=false

# If you need to increase the heap available to Java when packaging an Android app, you can use the below setting
# when ADT is run from another tool. (If run from the command line, just add -Xmx=2048m or similar to the command
# line within the ADT launch script..)
#JavaXmx=2048m

# For debugging, set this to 'true' and a file "adt.log" should be generated in your user's home folder
DebugOut=true

# To override the creation of an Android APK file, and to instead create an Android App Bundle, the below
# flag can be uncommented. Note that the bundle may end up with an "apk" file extension
CreateAndroidAppBundle=true

# When creating an Android App Bundle, this flag can be used to output the Android Studio project
# files in a subfolder of your build directory (rather than using a temporary location that gets
# cleaned up on exit).
#KeepAndroidStudioOutput=true

# For convenience, rather than using "-platformsdk" on the command line, these can be set up here:
AndroidPlatformSDK=C:\\Users\\yong2\\AppData\\Local\\Android\\Sdk
#iOSPlatformSDK=path_to_sdk

# JAVA_HOME is usually picked up from an environment variable but this can override it:
JAVA_HOME=C:\\Program Files\\Java\\jdk-17.0.3.1

# on macos platorms, use the native codesign task rather than trying to use ADT's internal code:
#UseNativeCodesign=true

# NOTE TO WINDOWS USERS: paths should be either in the form "C:\\Users\\etc", with two backslash characters, or using
# forwardslash characters instead such as "C:/Users/etc". If a single backslash is used, the config file is ignored.
```

**Comment by marchbold** [comment] 2022-07-11 09:59
@ronyarbiv Not sure if you found answers to this but the size difference is due to AIR not packaging unnecessary jars/resources with the APK. There used to be content included twice that has been cleaned up. 

Using an old 1024 bit certificate is still possible, just a bit tedious. You need to use java 11 to build your app, and then switch to java 1.8 to sign it. 

However if you move to Play Signing then you can upload your old certificate to the play console and google will handle that part of it for you. You can then create a new 2048 bit certificate to sign your app just for uploading to the play store.

**Comment by marchbold** [comment] 2022-07-11 10:02
@yong2khoo88 I believe this issue is caused by FlashBuilder. It seems to use the old build method regardless. Personally I'd highly recommend moving away from that very old IDE and trying something new?

**Comment by yong2khoo88** [comment] 2022-07-11 10:43
> @yong2khoo88 I believe this issue is caused by FlashBuilder. It seems to use the old build method regardless. Personally I'd highly recommend moving away from that very old IDE and trying something new?

noted. shall do this in next time.

i made up my mind having the last attempt just now.
Re-do all the steps again. Everytime i change adt.cfg, i have to restart Flash builder, clear cache.

After resolving `"/values/values.xml:3: error"` error thingy, i encounter [another](https://github.com/airsdk/Adobe-Runtime-Support/issues/1589). But great to know the adt.log at least show some hints.

 Finally have it done.

One thing probably trivial is
![image](https://user-images.githubusercontent.com/5007089/178246941-b6d3ce39-141e-4da5-98dd-bb4b615d26dd.png)
i originally didnt tick the package which is not used. not sure that cause the errors.

But anyway, thanks for the all the comments and guides throughout github issues.

**Comment by jacobpuzonicognite** [comment] 2022-11-03 08:23
hi. we're also encountering the same error. our code is actionscript 3.0 and is based on AIR. we're using vscode to compile the app. AndroidPlatformSDK is pointed at the one provided by Android Studio. we have also tried also versions of Java including the ones from Android Studio, but so far we're still encountering the error. When we remove all ANEs that uses androidx.core, the app gets compiled successfully. The ANEs that we use with androidx.core dependencies are Notifications and CameraRollExtended. hoping for any insights on this.

**Comment by vinodh143** [comment] 2023-05-17 14:10
@marchbold Could you please explain me, what is the new Build process? could you share the step by step guide to adapt the new Build process? it would be great help, we are using the latest Facebook SDK from Distriqt , it forcefully included the Androidx aNE's, this is where the problem starts, We are using the AiRSDK air_sdk_33_1_1_929, Java version is jdk1.8.0_171,
The build system we use is Ant Build system,. here what we are missing? please help us to resolve the issue

Below are the error we are seeing when we try to create the APK

[java] aapt tool failed:/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/cb805418-2039-41bf-af85-7ca918d24242/savedstate-1.2.1-res/values/values.xml:3: error: Found tag id where item is expected
     [java] 
     [java] /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/cb805418-2039-41bf-af85-7ca918d24242/lifecycle-viewmodel-2.6.1-res/values/values.xml:3: error: Found tag id where item is expected
     [java] 
     [java] /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/cb805418-2039-41bf-af85-7ca918d24242/lifecycle-runtime-2.6.1-res/values/values.xml:3: error: Found tag id where item is expected
     [java] 
     [java] /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/cb805418-2039-41bf-af85-7ca918d24242/activity-1.7.0-res/values/values.xml:4: error: Found tag id where item is expected

**Comment by apofis1969** [comment] 2023-05-17 17:20
hi @vinodh143, did you try with SDK 50.2.2.5 and Java 11? I do not get any build errors. 
My adt.cfg file has these additions as recommended by Adobe Air.
`# For convenience, rather than using "-platformsdk" on the command line, these can be set up here:
AndroidPlatformSDK=/Users/myMac/Library/Android/sdk
#iOSPlatformSDK=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk

# JAVA_HOME is usually picked up from an environment variable but this can override it:
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.0.16.1.jdk/Contents/Home`

Maybe this helps

**Comment by marchbold** [comment] 2023-05-18 02:08
@vinodh143 The new build process uses gradle. It requires that you have installed the android sdk and either used the default install location or configured AIR to use it through either the AIR SDK Manager or adt.cfg directly. 

If you don't then it will fall back to the legacy build method which doesn't support a lot of modern features and we don't support it with our extensions any longer. 

Also note that you can force the legacy build method through the app descriptor flag so ensure you aren't doing that either.

**Closed** 2023-10-25 10:21 UTC
Labels: Bug

**Comment by rdefalco** [comment] 2024-01-31 09:50
Just to add some late context, maybe useful for someone.

In Flash Builder, to be able to debug on Android device via USB, we had to add the parameter in the Debug Configurations, under Customize Launch

![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/1823019/e258b6f2-4a33-4535-a117-c155ea3c6380)

Even if AndroidPlatformSDK was set in adt.cfg, it didn't work and always led to the invocation of "aapt.exe" and the consequent errors citing "values.xml", while adding the "platformsdk" custom parameter seemed to solve the issue.
