### ISSUE TITLE
NetStream rtmp live video stream not working with Android since Adobe Air 33.1

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#300] opened 2020-04-21 14:17 UTC
## Problem Description

The NetStream feature does not work with Android since Adobe Air 33.1
If Android is the Receiver of a rtmp live video stream the sound and video transmission is broken. Tried a lot of workarounds, different rendering modes, but no chance. All emails I sent to Harman stay without any response and this problem is still not fixed.
Maybe someone here has an idea or solution.
The last working version of the Air SDK is 33.0.2.338

https://tracker.adobe.com/#/view/AIR-4198908

**Comment by ajwfrost** [comment] 2020-09-24 10:58
@apofis1969 just checking, is this a duplicate of #330 ? have just found this one by searching for 'rtmp'...

**Closed** 2021-11-07 09:57 UTC
