### ISSUE TITLE
mxmlc ASC 2.0 JDK illegal reflective access

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#516] opened 2020-11-06 21:09 UTC
## Problem Description

* AIR SDK 33.1.1.300
* Windows and Mac

When I use mxmlc with the JDK 15.0.1, I have this warning

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.common.base.internal.Finalizer (file:/C:/AIRSDK_Compiler/lib/guava-r08.jar) to field java.lang.Thread.inheritableThreadLocals
WARNING: Please consider reporting this to the maintainers of com.google.common.base.internal.Finalizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

## Steps to Reproduce

`mxmlc Main.as -o main.swf`

## Known Workarounds

use flex AIR SDK ( ASC 1.0 )

**Comment by PrimaryFeather** [comment] 2021-06-23 09:35
I'm getting the same warning with the latest AIR version (33.1.1.476), running with JDK 12.0.2 – was there anything specific you did to fix this?

**Comment by ajwfrost** [comment] 2021-06-23 15:12
@PrimaryFeather do you also get it being reported from within the 'guava' jar file? Not sure where `guava-r08.jar` is being called from it's something that's still in the SDK because it was in it when Adobe were shipping - but for APK generation, we are using `guava-22.0.jar` which is actually renamed and put into the SDK's `lib/android/lib` folder.

So it might be that you can copy the one from the subfolder into this lib folder - not sure whether that would resolve the issue though.

I'd be interested if there's a call stack so that we could see what's actually calling this library!

**Comment by PrimaryFeather** [comment] 2021-06-23 15:56
Thanks a lot for your input, Andrew!
Yes, it's also `guava-r08.jar` that's reported as the cause!

It's so weird ... I just copied `guava.jar` from the `lib/android/lib` folder directly into `lib` and renamed it `guava-r08.jar` (replacing the existing one), as you suggested — and I still get the same warning. Just that now, there's also a follow-up error. 🙃

What's positive about that error, though, is that it comes with a stack trace. :wink:
Here's the output I'm getting:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.common.base.internal.Finalizer (file:/Users/redge/Dropbox/Development/library/flash/air/air-33-beta/lib/guava-r08.jar) to field java.lang.Thread.inheritableThreadLocals
WARNING: Please consider reporting this to the maintainers of com.google.common.base.internal.Finalizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.MapMaker.softValues()Lcom/google/common/collect/MapMaker;
        at com.adobe.flash.compiler.internal.projects.CompilerProject.<init>(CompilerProject.java:116)
        at com.adobe.flash.compiler.internal.projects.ASProject.<init>(ASProject.java:71)
        at com.adobe.flash.compiler.internal.projects.FlexProject.<init>(FlexProject.java:104)
        at com.adobe.flash.compiler.internal.projects.FlexProject.<init>(FlexProject.java:122)
        at com.adobe.flash.compiler.clients.MXMLC.<init>(MXMLC.java:338)
        at com.adobe.flash.compiler.clients.COMPC.<init>(COMPC.java:53)
        at com.adobe.flash.compiler.clients.COMPC.staticMainNoExit(COMPC.java:74)
        at com.adobe.flash.compiler.clients.COMPC.main(COMPC.java:62)
The terminal process "/usr/bin/java '-jar', '/Users/redge/.vscode/extensions/bowlerhatllc.vscode-nextgenas-1.7.1/bin/asconfigc.jar', '--sdk', '/Users/redge/Dropbox/Development/library/flash/air/air-33-beta', '--debug=true', '--project', '/Users/redge/Development/starling/starling/asconfig.json'" terminated with exit code: 1.
```

Removing the file from `lib` altogether yields the following error:

```
Error: Unable to initialize main class com.adobe.flash.compiler.clients.COMPC
Caused by: java.lang.NoClassDefFoundError: com/google/common/base/Function
The terminal process "/usr/bin/java '-jar', '/Users/redge/.vscode/extensions/bowlerhatllc.vscode-nextgenas-1.7.1/bin/asconfigc.jar', '--sdk', '/Users/redge/Dropbox/Development/library/flash/air/air-33-beta', '--debug=true', '--project', '/Users/redge/Development/starling/starling/asconfig.json'" terminated with exit code: 1.
```

I don't know if that's any help to you? If there is anything else I can try out to help you get to the root of the issue, just let me know.

**Comment by ajwfrost** [comment] 2021-06-24 08:39
Ah okay thanks - so this is a compiler dependency.. it looks like we may be using two different Guava libraries - the first in the root 'lib' folder is then used by the Flex/AS3 compiler, the second in the 'android/lib' subfolder is used during APK creation.

Just looking at https://github.com/google/guava
it looks like there's a more recent version available at the below link, in the flavour that should be valid for the A3 compiler:
http://search.maven.org/remotecontent?filepath=com/google/guava/guava/23.0/guava-23.0.jar
but having just tried it, this is giving the same issues.


So ...
- currently this is just a warning
- but to eliminate it, we will need to update the Guava library, and that will also require us to update the AS3 compiler
- so no quick-fix I'm afraid (other than using an earlier JRE for compilation)

I'll reopen this issue as it will become a problem at some point once these warnings turn into errors, and we'll add a task to our internal tracker on the AS3 compiler side of things....

thanks

**Comment by PrimaryFeather** [comment] 2021-06-24 11:59
Thanks for having a look at this issue, Andrew! Yes, it's only a warning right now, so no show-stopper and definitely not the highest priority. But it's good to have it checked and documented for future reference. :smile: Cheers!

**Comment by ajwfrost** [comment] 2021-06-29 13:25
FYI one of the team had a look into this, we've made an update to the Guava library to backport the appropriate changes to avoid that warning. And then it complained about a similar illegal reflection within the AS3 compiler itself, which is just where it's trying to work out the character encoding used by the console (quite why there's no public API to find that out, I don't know). Upshot is: we can remove the warning (change is only for Java 9+) but it's possible there may be some characters that then don't appear properly on a Window output if it's not set to the expected codepage..)

So - this will be updated in a future SDK.
thanks

**Comment by PrimaryFeather** [comment] 2021-06-30 11:08
Thanks a lot for looking into it, and for keeping us updated! Great to hear that this warning will go away eventually. :smile:
Keep up the great work!

**Comment by ajwfrost** [comment] 2021-07-20 15:31
Hi - are you able to check this using 33.1.1.554 or later please, it should have been fixed in that release. Please re-open the ticket if you still see the problem..
thanks

**Closed by ajwfrost** 2021-07-20 15:31 UTC

**Comment by PrimaryFeather** [comment] 2021-07-20 18:47
Yes, I can confirm that this issue has been fixed! I actually saw you mentioned this in the release notes, tried it out, but then forgot to report that in this issue. 

Thanks a lot for getting rid of this message!

**Comment by berlinMilo** [comment] 2022-01-19 11:49
Andrew, I'm using the latest air.sdk (33.1.1.713) with IntelliJ IDEA on Mac,
and getting the described warning again:
… 
WARNING: An illegal reflective access operation has occurred
… /lib/guava-r08.jar) to field java.lang.Thread.inheritableThreadLocals.
…

It feels strange till i'm just targeting iOS.
Thanks for your work!

**Comment by ajwfrost** [comment] 2022-01-19 12:20
Hi @berlinMilo  - do you know what version of Java you're running there?

The code shouldn't need to access that field unless it's running an older version of Java (before 9 I think) at which point those warnings/errors won't happen anyway.

On later Java versions, we're using the below constructor for the Thread object which allows us to set the 'inheritThreadLocals' parameter to false, without needing to then use reflective access...
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Thread.html#%3Cinit%3E(java.lang.ThreadGroup,java.lang.Runnable,java.lang.String,long,boolean)

thanks

**Comment by berlinMilo** [comment] 2022-01-19 13:04
Andrew, sorry for the alert. It was my fault, i was still running on an Amazon Corretto 1.8.
Changed it to Corretto 17 -> and the error is gone. I have just moved to IntelliJ after years with FDT.
So the toolchain is new and i'm still struggling in a few areas. sorry.

**Comment by ajwfrost** [comment] 2022-01-19 14:16
Okay no worries - I was a bit concerned that there was going to be another change in Java that we'd have to work around..!

cheers

**Comment by berlinMilo** [comment] 2022-01-19 14:25
OK. that answer was to quick.
Now i compiled to a different simulator-device with Corretto 17 -> 

[Development (module … mm2_0_jetbrains)]: WARNING: An illegal reflective access operation has occurred
[Development (module … mm2_0_jetbrains)]: WARNING: Illegal reflective access by com.google.common.base.internal.Finalizer (file:… /flexSDK_4_16_0_air33_1_1_713_harman/lib/guava-r08.jar) to field java.lang.Thread.inheritableThreadLocals

**Comment by berlinMilo** [comment] 2022-01-19 15:06
Ok.Now i checked the build-process - and it shows:

Error during native code-signing. Output of codesign tool is:
Signing app failed - unknown reason

this was originally why i was working on Corretto 1.8.
Now switching back to 1.8 now shows the same error.
I don't understand what is happening…
Any help appreciated.
milo

**Comment by ajwfrost** [comment] 2022-01-19 15:26
It may be that there is some caching going on within IntelliJ which is making it a bit confused? If you're using Java 1.8 it shouldn't do the native code-signing thing (unless you had manually opted in to that with the adt.cfg file)...

As to why it failed: typically this would be if you don't have the provided certificate installed into the Keychain tool with the appropriate code-signing capabilities ... you should be able to see the certificate in the Keychain tool (and it needs to have a private key associated with it) in order for the native 'codesign' process to find it..

thanks
