### ISSUE TITLE
ANE to see Context ExtensionContext.createExtensionContext not created 

### ISSUE THREAD

**Issue by kaizer1** [airsdk/Adobe-Runtime-Support#3425] opened 2024-08-24 10:29 UTC
after updating the version not to the latest, it stopped connecting to the context. In theory, the matter is in a different Android layout? But we are fighting with the whole team, but we cannot understand the reason

<extension xmlns="http://ns.adobe.com/air/extension/51.0">  - extension.xml - version 51 
<platform xmlns="http://ns.adobe.com/air/extension/51.0">  - platform.xml - version 51 
android library all update to max

my manifest file: 
<?xml version="1.0" encoding="utf-8" standalone="no" ?>

<application xmlns="http://ns.adobe.com/air/application/51.0">
  <id>KiddoMagictestane</id>
  <versionNumber>1.1.1</versionNumber>
  <filename>KiddoMagic Test ANE</filename>
  <description/>
  <name>KiddoMagic Test ANE</name>
  <copyright/>
  <initialWindow>
    <content>TestAne.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>gpu</renderMode>
    <maximizable>true</maximizable>
    <minimizable>true</minimizable>
    <resizable>true</resizable>
    <autoOrients>true</autoOrients></initialWindow>
  <icon>
    <image192x192>AppIconsForPublish/192.png</image192x192>
    <image144x144>AppIconsForPublish/144.png</image144x144>
    <image96x96>AppIconsForPublish/96.png</image96x96>
    <image72x72>AppIconsForPublish/72.png</image72x72>
    <image48x48>AppIconsForPublish/48.png</image48x48>
    <image36x36>AppIconsForPublish/36.png</image36x36>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
    <manifestAdditions><![CDATA[<manifest>
	
	<application android:hardwareAccelerated="true"
	android:enabled="true"
	android:debuggable="true">
	
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN"/>
				<category android:name="android.intent.category.LAUNCHER"/>
			</intent-filter>
		</activity>
		
		<activity 
		android:name="com.kidshomealone.ane.WebIntentActivity" 
		android:label="Web_Intent_Activity"
		android:exported="true"
		android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
		android:configChanges="keyboardHidden|orientation|screenSize" />
		
		<activity
		android:name="com.android.billingclient.api.ProxyBillingActivity"
		android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
		android:exported="false"
		android:theme="@android:style/Theme.Translucent.NoTitleBar" />
		
		<activity 
		android:name="com.kidshomealone.ane.PlayerActivity"
		android:screenOrientation="sensorLandscape"
		android:exported="false"
		android:theme="@android:style/Theme.NoTitleBar.Fullscreen"/>
		
		<activity 
		android:name="com.kidshomealone.ane.browser.ui.browser.WebBrowserActivity"
		android:screenOrientation="sensorLandscape"
		android:exported="false"
		android:theme="@android:style/Theme.NoTitleBar.Fullscreen"/>
		
		<activity 
		android:name="com.kidshomealone.ane.promo.PromoWebViewActivity"
		android:screenOrientation="sensorLandscape"
		android:exported="false"
		android:theme="@android:style/Theme.NoTitleBar.Fullscreen"/>
	</application>
	
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.RECORD_AUDIO"/>
<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.VIBRATE"/>
<uses-permission android:name="com.android.vending.BILLING"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE"/>
</manifest>]]></manifestAdditions>
   <BuildLegacyAPK>true</BuildLegacyAPK>
  </android>
  <versionLabel/>
  <extensions>
    <extensionID>kiddo</extensionID>
  </extensions>
</application>

The application is built and launched, but calls from Android ANE (android java library to wrapper to ANE ) do not work

**Comment by ajwfrost** [comment] 2024-08-25 11:57
This might be a platform-specific issue .. what are you running it on, and how are you packaging the APK?

So e.g. if the APK is built for armv8, or if you're using an AAB file, then it might be that the ANE doesn't have support for armv8 (Android-ARM64) built in...?

Generally there should be some output information via logcat that you can get, e.g. if you run
```
adt -deviceLog -platform android
```
then you'll see the ADB logcat logging from Android, you can redirect it to a file e.g.
```
adt -deviceLog -platform android > logfile.txt 2>&1
```
and then open your application; once it's got to the failure point, type "quit" (and hit enter) and the logging should stop.

thanks

**Comment by kaizer1** [comment] 2024-08-25 14:49
I compile and android armv8 compile with this command . But it compiles everything fine and there is no error in the logs. It just does not return the context to me, that's the problem

**Comment by ajwfrost** [comment] 2024-08-25 17:12
Hi

Would you be able to share us the APK file that you've created with this, so that we can run it and inspect it with the debug tools/runtime to see what's happening?
https://transfer.harman.com/requests/Y76yJJE82QlYI8gptQHrU0

thanks

**Comment by kaizer1** [comment] 2024-08-25 17:16
Yes, of course, just a second

**Comment by kaizer1** [comment] 2024-08-25 19:14
i send apk ( two hour later )

**Comment by ajwfrost** [comment] 2024-08-25 21:12
Thanks - received this and can run it, we can see the extension's SWF data is being loaded so it looks like it's packaged properly and the platform details are all fine. The Java code seems to have been compiled in (classes2.dex).

I think we'll need to put in a debug runtime and re-package the APK, in order to find out what's actually happening. Just to check though, to trigger a call to create an ExtensionContext and call a method in the ANE, do we have to press any particular button, or just anything?!

thanks

**Comment by kaizer1** [comment] 2024-08-26 02:26
Yes, there are several buttons made there and any of them calls a certain function in the attached () android library the corresponding command. So, now the command is not called in any way... For the reason that we do not create a context, if you run the source code in animat - then you can see it - I can upload the source code to the repository and give you a link so that you can try to compile it yourself

**Comment by kaizer1** [comment] 2024-08-29 08:29
https://dev.easybits.net/public/ane.debug  Good day, I prepared everything and posted it here (open access) and described in the file  Environment.txt  how to assemble it so that you could track the error (incorrect operation of the context). I am very glad that you are helping to sort out this situation

**Comment by kaizer1** [comment] 2024-08-30 13:51
?????

**Comment by kaizer1** [comment] 2024-08-30 14:06
@ajwfrost please help me. My project is at a dead end

**Comment by ajwfrost** [comment] 2024-08-30 14:56
Sorry, we're working through a fair backlog of issues at the moment, will try to get you some feedback soon..

**Comment by kaizer1** [comment] 2024-08-30 15:14
Thank you, I understand.

**Comment by ajwfrost** [comment] 2024-08-30 16:39
Just a couple of notes - we've started looking at it now, and reproduced it having built it here.

1. If you want to build your extension library, without Animate, you can use the below line - the benefit of this being, you can include trace statements by setting the debug value to true.
```
compc -load-config=i:\Adobe\AIR51\sdk2\AIRSDK\frameworks\air-config.xml -include-sources="." -debug=true -swf-version=50 -output=library.swc
```

2. Your app descriptor was using the old multidex support library? it should really be using the new androidx one now:
```
	<application android:hardwareAccelerated="true"
	android:name="android.support.multidex.MultiDexApplication"
	android:enabled="true"
	android:debuggable="true">
```
should be
```
	<application android:hardwareAccelerated="true"
	android:name="androidx.multidex.MultiDexApplication"
	android:enabled="true"
	android:debuggable="true">
```


The actual problem appears to be with packaging i.e. within ADT. Because it's not generating the build system properly - your "classes.jar" isn't being provided to Gradle for building... so we should be able to do some debugging within ADT to see what's going wrong... will try to either let you know if there's a workaround, or get a fix for this into our forthcoming release.

thanks

**Comment by kaizer1** [comment] 2024-08-30 17:33
Thank you very much, I will wait

**Comment by ajwfrost** [comment] 2024-08-31 06:35
Okay so actually, not a problem with ADT, I had forgotten that the extension JAR file got moved from the ANE-based sub-project into the main project, and renamed to ExtensionID.jar...

When running it with some debugging, we get the output
```
unable to load custom class com.kidshomealone.ane.KiddoMagicExtension
```

And looking at the classes.jar file that you're generating as part of your 'Android' build, it doesn't actually contain any of your own classes... something is very wrong with the way that you are creating that library file.

I've just been trying to find some tutorial on this because I know we have one somewhere, but can't find it - potentially it was just description within an issue like this and never made it out separately. But to create the classes.jar file for an Android ANE, I would suggest using Android Studio to create a library project. If you unzip an .aar file that this will generate, you can get at the JAR file - or it should be possible with our latest SDK to use the .aar file itself.
See https://developer.android.com/studio/projects/android-library

thanks

**Comment by kaizer1** [comment] 2024-08-31 06:40
Thank you, but the thing is that I specialize in Android. And there I create exactly what is needed - a library. It's very strange, but thank you very much for your help, now I know which way to look

**Comment by kaizer1** [comment] 2024-08-31 06:41
I'll check everything again and close (in a day or two) this thread, okay?

**Comment by ajwfrost** [comment] 2024-08-31 07:05
Sure that's fine. FYI, I didn't know exactly how it was building/packaging, but was just checking the contents of the classes.jar file using "unzip -l" to list the .class files. And the ones with your ANE package names didn't appear to be there.

thanks

**Closed** 2024-09-01 10:44 UTC
Labels: Bug
